dubbo:
  application:
    name: shoppro-product-service
  registry:
    protocol: zookeeper
    address: 10.36.141.66:2181
  protocol:
    port: 20880

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopprodubbo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123
mybatis:
  mapper-locations:  classpath:/mapper/*.xml
