#dubbo.application.name=shoppro-background
#dubbo.registry.protocol=zookeeper
#dubbo.registry.address=10.36.141.66:2181
#server.port=8888
dubbo:
  application:
    name: shoppro-background
  registry:
    protocol: zookeeper
    address: 120.78.77.179:2181
server:
  port: 8888
#####开发时不要缓存####
spring:
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#####分布式文件系统相关####
fdfs:
  connect-timeout: 3000
  so-timeout: 5000
  thumb-image:
    width: 100
    height: 100
  tracker-list: 120.78.77.179:22122
  pool:
    jmx-enabled: false
#####自定义上传图片路径前缀###
image:
  server: http://120.78.77.179/